from enum import Enum
from typing import Optional, List
from pydantic import BaseModel, Field


class SceneStatus(str, Enum):
    PENDING = "pending"
    PROCESSING = "processing"
    COMPLETED = "completed"
    FAILED = "failed"

class AssetStatus(str, Enum):
    MISSING = "missing"
    GENERATING = "generating"
    READY = "ready"
    ERROR = "error"


class SceneResponse(BaseModel):
    """Represents a single modular scene in the video pipeline."""
    scene_id: str = Field(..., description="Unique ID for this scene (e.g., project_id_scene_001)")
    project_id: str = Field(..., description="ID of the parent project/document")
    scene_order: int = Field(..., description="Sequential order in the timeline (1-indexed)")
    
    heading: str = Field(..., description="Scene title or section heading")
    narration_text: str = Field(..., description="Text to be spoken by TTS")
    visual_prompt: str = Field(..., description="Prompt to generate the scene image")
    subtitle_text: str = Field(..., description="Clean text for on-screen subtitles")
    
    estimated_duration: Optional[float] = Field(None, description="Initial LLM estimate (seconds)")
    actual_duration: Optional[float] = Field(None, description="Exact length of generated audio (seconds)")
    
    # Asset paths relative to the storage directory or absolute paths
    audio_path: Optional[str] = Field(None, description="Path to generated TTS audio (.wav/mp3)")
    image_path: Optional[str] = Field(None, description="Path to generated visual image (.png/jpg)")
    clip_path: Optional[str] = Field(None, description="Path to rendered scene clip (.mp4)")
    
    # Phase 4: Educational Visual Generation extensions
    concept_summary: Optional[str] = Field(None, description="Extracted core concept of the scene")
    visual_type: Optional[str] = Field(None, description="Chosen visual type (e.g. labeled diagram, infographic)")
    style_preset: Optional[str] = Field("cinematic_educational", description="Chosen style preset")
    enriched_prompt: Optional[str] = Field(None, description="Detailed prompt generated by the planner")
    negative_prompt: Optional[str] = Field(None, description="Negative prompt to reduce bad outputs")
    prompt_candidates: Optional[dict[str, str]] = Field(None, description="Style-to-prompt mapping for variants")
    debug_logs: List[str] = Field(default_factory=list, description="History of prompt transformations")
    selected_prompt: Optional[str] = Field(None, description="The prompt actually selected for rendering")
    image_provider: Optional[str] = Field(None, description="Provider used for generation (e.g. pollinations)")
    image_score: Optional[float] = Field(None, description="Quality score of the generated image")
    
    image_status: AssetStatus = Field(default=AssetStatus.MISSING)
    audio_status: AssetStatus = Field(default=AssetStatus.MISSING)
    clip_status: AssetStatus = Field(default=AssetStatus.MISSING)
    
    last_updated: Optional[str] = Field(None, description="ISO timestamp of last modification")
    status: SceneStatus = Field(default=SceneStatus.PENDING, description="Overall scene asset status")
    error_message: Optional[str] = None


class ProjectMetadata(BaseModel):
    """Tracks the state of all scenes for a project."""
    project_id: str
    total_scenes: int = 0
    scenes: List[SceneResponse] = []
    
    # Timeline paths
    timeline_path: Optional[str] = Field(None, description="Path to the timeline JSON/TXT definition")
    final_video_path: Optional[str] = Field(None, description="Path to the final assembled video export")


class AssetGenerationRequest(BaseModel):
    """Optional configuration for asset generation."""
    voice: str = Field("en-US-AriaNeural", description="TTS Voice ID")
    image_style: str = Field("cinematic_educational", description="Base style preset")
    custom_prompt: Optional[str] = Field(None, description="A UI-overridden custom prompt to use for generation")
    image_provider: Optional[str] = Field(None, description="Request a specific provider (stabilityai, gemini, pollinations)")
    
class VisualConceptResponse(BaseModel):
    """Output from the Visual Concept Extraction module."""
    concept_summary: str
    visual_type: str
    enriched_image_prompt: str
    negative_prompt: str
    prompt_candidates: dict[str, str] = Field(default_factory=dict)
    debug_logs: List[str] = Field(default_factory=list)
    optional_labels: List[str] = []
    optional_composition_notes: str = ""
